package world

import (
	"bufio"
	"os"
	"strconv"
	"strings"
	"testing"
)

// TestJavaHashSetOrderMatchesVanilla checks the HashSet<BlockPos> emulation
// against vanilla's own hash table rather than against a reading of it.
// VegetationPatchFeature collects ground cells into a plain HashSet and
// distributeVegetation draws one nextFloat per entry in iteration order, so the
// order decides which cell gets which vegetation roll: a wrong order permutes
// the rolls across cells that are all otherwise identical, which is exactly the
// shape of the nested-vegetation residual (moss_carpet 64.6% agreement, azalea
// 66.7%, short_grass 68.3%, against 93.2% for the moss ground they sit on).
//
// The fixture is generated by tools/VanillaBlockPosHashSetOrder.java, which
// inserts disc-shaped position sets - the shape a real patch produces - and
// prints the resulting iteration order. Sizes straddle every HashMap resize
// threshold, because a port that computes the table's final capacity wrong only
// diverges at those boundaries.
//
// One thing this deliberately does not cover: HashSet.add drops a position that
// is already in the table, while production's patchSet is a plain append. That
// is unreachable today because each scanned column contributes at most one
// ground cell, so every case here holds distinct positions. If a future change
// lets a column append twice, the fix is the dedup, not a filter in this test.
func TestJavaHashSetOrderMatchesVanilla(t *testing.T) {
	cases := readHashOrderFixture(t, "testdata/java_blockpos_hashset_order.txt")
	if len(cases) == 0 {
		t.Fatal("the fixture holds no cases")
	}
	failed := 0
	for _, tc := range cases {
		got := javaHashSetOrder(tc.inserted)
		if len(got) != len(tc.iterated) {
			t.Errorf("case %d (%d positions): order returned %d entries, vanilla %d",
				tc.index, len(tc.inserted), len(got), len(tc.iterated))
			failed++
			continue
		}
		for i := range got {
			if got[i] != tc.iterated[i] {
				t.Errorf("case %d (%d positions): first divergence at %d, ours %v, vanilla %v",
					tc.index, len(tc.inserted), i, got[i], tc.iterated[i])
				failed++
				break
			}
		}
	}
	if failed == 0 {
		t.Logf("%d insertion sets, every one iterated exactly as vanilla does", len(cases))
		return
	}
	t.Fatalf("%d of %d sets iterate differently from vanilla", failed, len(cases))
}

type hashOrderCase struct {
	index    int
	inserted [][3]int
	iterated [][3]int
}

func readHashOrderFixture(t *testing.T, path string) []hashOrderCase {
	t.Helper()
	file, err := os.Open(path)
	if err != nil {
		t.Fatalf("opening %s: %v", path, err)
	}
	defer file.Close()
	var cases []hashOrderCase
	current := hashOrderCase{index: -1}
	closeCurrent := func() {
		if current.index >= 0 {
			cases = append(cases, current)
		}
		current = hashOrderCase{index: -1}
	}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1<<16), 1<<16)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		fields := strings.Fields(line)
		switch fields[0] {
		case "case":
			if len(fields) != 3 {
				t.Fatalf("%s: malformed header %q", path, line)
			}
			closeCurrent()
			current.index = atoiField(t, line, fields[1])
		case "i", "o":
			if len(fields) != 4 {
				t.Fatalf("%s: malformed record %q", path, line)
			}
			pos := parsePos(t, line, fields)
			if fields[0] == "i" {
				current.inserted = append(current.inserted, pos)
			} else {
				current.iterated = append(current.iterated, pos)
			}
		default:
			t.Fatalf("%s: unknown record %q", path, line)
		}
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	closeCurrent()
	return cases
}

func parsePos(t *testing.T, line string, fields []string) [3]int {
	t.Helper()
	return [3]int{
		atoiField(t, line, fields[1]),
		atoiField(t, line, fields[2]),
		atoiField(t, line, fields[3]),
	}
}

func atoiField(t *testing.T, line, value string) int {
	t.Helper()
	n, err := strconv.Atoi(value)
	if err != nil {
		t.Fatalf("malformed record %q: %v", line, err)
	}
	return n
}
